{
  bind = [
    "$mainMod,Return,exec,ghostty"
    "$mainMod,K,exec,list-keybinds"
    "$mainMod ,R,exec,rofi-launcher"
    "$mainMod,Space,exec,rofi -show drun"
    "$mainMod SHIFT,W,exec,web-search"
    "$mainMod ALT,W,exec,wallsetter"
    "$mainMod SHIFT,N,exec,swaync-client -rs"
    "$mainMod,Y,exec,ghostty -e yazi"
    "$mainMod,E,exec,emopicker9000"
    "$mainMod,S,exec,screenshootin"
    "$mainMod,D,exec,discord"
    "$mainMod,O,exec,obs"
    "$mainMod,C,exec,hyprpicker -a"
    "$mainMod,G,exec,gimp"
    "$mainMod shift,T,exec,pypr toggle term"
    "$mainMod,T,exec, thunar"
    "$mainMod,M,exec,pavucontrol"
    "$mainMod,C,killactive,"
    "$mainMod,P,pseudo,"
    "$mainMod,V,exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy"
    "$mainMod SHIFT,I,togglesplit,"
    "$mainMod,F,fullscreen,"
    "$mainMod SHIFT,F,togglefloating,"
    "$mainMod ALT,F,workspaceopt, allfloat"
    "$mainMod SHIFT,C,exit,"
    "$mainMod SHIFT,right, resizeactive, 10 0"
    "$mainMod SHIFT,left, resizeactive, -10 0"
    "$mainMod SHIFT,up, resizeactive, 0 -10"
    "$mainMod SHIFT,down, resizeactive, 0 10"
    "$mainMod SHIFT,h,movewindow,l"
    "$mainMod SHIFT,l,movewindow,r"
    "$mainMod SHIFT,k,movewindow,u"
    "$mainMod SHIFT,j,movewindow,d"
    "$mainMod ALT, left, swapwindow,l"
    "$mainMod ALT, right, swapwindow,r"
    "$mainMod ALT, up, swapwindow,u"
    "$mainMod ALT, down, swapwindow,d"
    "$mainMod ALT, 43, swapwindow,l"
    "$mainMod ALT, 46, swapwindow,r"
    "$mainMod ALT, 45, swapwindow,u"
    "$mainMod ALT, 44, swapwindow,d"
    "$mainMod,left,movefocus,l"
    "$mainMod,right,movefocus,r"
    "$mainMod,up,movefocus,u"
    "$mainMod,down,movefocus,d"
    "$mainMod,h,movefocus,l"
    "$mainMod,l,movefocus,r"
    "$mainMod,k,movefocus,u"
    "$mainMod,j,movefocus,d"
    "$mainMod,1,workspace,1"
    "$mainMod,2,workspace,2"
    "$mainMod,3,workspace,3"
    "$mainMod,4,workspace,4"
    "$mainMod,5,workspace,5"
    "$mainMod,6,workspace,6"
    "$mainMod,7,workspace,7"
    "$mainMod,8,workspace,8"
    "$mainMod,9,workspace,9"
    "$mainMod,0,workspace,10"
    # "$mainMod ,SHIFT,Space,movetoworkspace,special"
    # "$mainMod,SHIFT,Return,togglespecialworkspace"
    "$mainMod SHIFT,1,movetoworkspace,1"
    "$mainMod SHIFT,2,movetoworkspace,2"
    "$mainMod SHIFT,3,movetoworkspace,3"
    "$mainMod SHIFT,4,movetoworkspace,4"
    "$mainMod SHIFT,5,movetoworkspace,5"
    "$mainMod SHIFT,6,movetoworkspace,6"
    "$mainMod SHIFT,7,movetoworkspace,7"
    "$mainMod SHIFT,8,movetoworkspace,8"
    "$mainMod SHIFT,9,movetoworkspace,9"
    "$mainMod SHIFT,0,movetoworkspace,10"
    "$mainMod CONTROL,right,workspace,e+1"
    "$mainMod CONTROL,left,workspace,e-1"
    "$mainMod,mouse_down,workspace, e+1"
    "$mainMod,mouse_up,workspace, e-1"
    "ALT,Tab,cyclenext"
    "ALT,Tab,bringactivetotop"
    ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
    ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
    " ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
    ",XF86AudioPlay, exec, playerctl play-pause"
    ",XF86AudioPause, exec, playerctl play-pause"
    ",XF86AudioNext, exec, playerctl next"
    ",XF86AudioPrev, exec, playerctl previous"
    ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
    ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    # ",XF86MonBrightnessDown,exec,light -U 5"
    # ",XF86MonBrightnessUp,exec,light -A 5"

    ",PRINT, exec, grimblast copysave area ~/Images/screenshots/screenshot_$(date +%Y%m%d_%H%M%S).png"
    "$mainMod SHIFT, PRINT, exec, grimblast copysave output~/Images/screenshots/screenshot_$(date +%Y%m%d_%H%M%S).png"
  ];

  bindm = [
    "$mainMod, mouse:272, movewindow"
    "$mainMod, mouse:273, resizewindow"
  ];
}
