name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔒 Security'
    labels:
      - 'security'
      - 'vulnerability'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'optimization'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
  - title: '🎨 Styling'
    labels:
      - 'style'
      - 'ui'
      - 'ux'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'security'
  default: patch

autolabeler:
  - label: 'feature'
    branch:
      - '/^feat(ure)?[/-].+/'
    title:
      - '/^feat(\(.+\))?:.+/i'
  - label: 'bug'
    branch:
      - '/^fix[/-].+/'
    title:
      - '/^fix(\(.+\))?:.+/i'
  - label: 'documentation'
    branch:
      - '/^docs?[/-].+/'
    title:
      - '/^docs?(\(.+\))?:.+/i'
    files:
      - '*.md'
      - 'docs/**/*'
  - label: 'chore'
    branch:
      - '/^chore[/-].+/'
    title:
      - '/^chore(\(.+\))?:.+/i'
  - label: 'dependencies'
    files:
      - 'package.json'
      - 'Cargo.toml'
      - 'go.mod'
      - 'requirements.txt'
      - 'build.zig.zon'

template: |
  ## What's Changed

  $CHANGES
  
  ## New Contributors
  
  $CONTRIBUTORS
  
  ## Installation
  
  Download the appropriate binary for your platform from the assets below.
  
  ### Verify checksums
  
