  security-scan:
    name: Security Scanning
    needs: lint
    runs-on: ubuntu-latest

    # Required for uploading SARIF to Code Scanning
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check flake lock
        run: |
          if ! nix flake check --print-build-logs; then
            echo "Flake check failed. Consider running 'nix flake update' to update inputs."
            exit 1
          fi

      - name: Show versions
        run: |
          nix flake metadata --json | jq '.locks.nodes | to_entries[] | {name: .key, url: .value.original.url, rev: .value.locked.rev}'
          
      - name: Build all NixOS configurations
        run: |
          nix build .#nixosConfigurations.laptop.config.system.build.toplevel --print-build-logs

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif

      # Skip upload on forked PRs (tokens are read-only on forks)
      - name: Upload Trivy results to GitHub Security
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
 
