---
name: Issue Management

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]
  workflow_dispatch: {}

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    name: Auto Assign Issues
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.repository_owner }}

  label-bug:
    name: Label Bug Reports
    if: contains(github.event.issue.body, 'bug') || contains(github.event.issue.title, 'bug')
    runs-on: ubuntu-latest
    steps:
      - name: Add bug label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['bug']
            })
